# @package _group_
kwargs:
  gpus: -1
  accelerator: ddp
  max_epochs: 800
  gradient_clip_val: 1
  log_gpu_memory: None
  limit_train_batches: 60000
  val_check_interval: 1.0
  log_every_n_steps: 40
  precision: 32
  terminate_on_nan: False
  check_val_every_n_epoch: 30
  num_sanity_val_steps: 10
  replace_sampler_ddp: False
checkpoint_kwargs:
  verbose: True
  save_top_k: 2
  save_last: True
  period: 1
  monitor: val_ssim_fid100_f1_total_mean
  mode: max