indir: ${env:TORCH_HOME}/datasets/afhq/test/test_256_with_mask/cat/random_thick_256  # to be overriden in CLI
outdir: ${env:TORCH_HOME}/outputs/our/inner_features_our  # to be overriden in CLI

model:
  path: ${env:TORCH_HOME}/experiments/lama-celebahq_full_config_cat_random_seed2_aug_fix_m_cl2l_cg2l_fix_UD_wo_fm_stage_two_aug_no_fix_wo_fm_50val/22-27-06  # to be overriden in CLI
  checkpoint: model1.ckpt

dataset:
  kind: default
  img_suffix: .png
  pad_out_to_modulo: 8

device: cuda
out_key: inpainted
#levels: [5,6,8,10,12]
levels: [5,6,7,8,9,10,11,12,13]
hole_radius: 60
slice_channels: false