indir: ${env:TORCH_HOME}/datasets/afhq/test/test_256_with_mask/cat/random_thick_256  # to be overriden in CLI
outdir: ${env:TORCH_HOME}/outputs/feature_visualization/cat_all_data_best_combine  # to be overriden in CLI

model:
  path: /mnt/d/post/codes/lama/experiment/big-lama-place2_full_config_cat_data_allx3_seed0_flip_fix_cl2l_cg2l_ud_wo_fm_stage_two_tsa_all/18-15-12  # to be overriden in CLI
  checkpoint: cat_all_best_combine.ckpt

dataset:
  kind: default
  img_suffix: .png
  pad_out_to_modulo: 8

device: cuda
out_key: inpainted
#levels: [5,6,8,10,12]
levels: [21, 22]
hole_radius: 60
slice_channels: false