generator_kind: random

# mask_generator_kwargs:
#   irregular_proba: 1
#   irregular_kwargs:
#     min_times: 1
#     max_times: 5
#     max_width: 100
#     max_angle: 4
#     max_len: 200

#   box_proba: 0.3
#   box_kwargs:
#     margin: 10
#     bbox_min_size: 30
#     bbox_max_size: 150
#     max_times: 3
#     min_times: 1

#   segm_proba: 0
#   squares_proba: 0

#   variants_n: 5

# max_masks_per_image: 1

# cropping:
#   out_min_size: 256
#   handle_small_mode: upscale
#   out_square_crop: True
#   crop_min_overlap: 1

# max_tamper_area: 0.5


mask_generator_kwargs:
  irregular_proba: 1
  irregular_kwargs:
    max_angle: 4
    max_len: 200 # 200 -> 220
    max_width: 100 # 100 -> 150
    max_times: 7 # 5 -> 10
    min_times: 1 # 1 -> 2
  box_proba: 1
  box_kwargs:
    margin: 10
    bbox_min_size: 30 
    bbox_max_size: 150  # 150 -> 220
    max_times: 7 # 4 -> 8
    min_times: 1 # 1 -> 2
  segm_proba: 0
  squares_proba: 0

  variants_n: 5

max_masks_per_image: 1

cropping:
  out_min_size: 256
  handle_small_mode: upscale
  out_square_crop: True
  crop_min_overlap: 1

max_tamper_area: 0.9